config/routes.rb
Rails.application.routes.draw do
  resources :guest_house_reservations

  resources :hall_reservations

  resources :car_reservations

  get 'sessions/new'

root :to => "sessions#new"
  resources :complaints

  resources :users
  resources :home
  resources :sessions 
  get "login", :to => "sessions#new"

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :user
end

app/models/login.rb
class Login < ActiveRecord::Base
  belongs_to :user

def remember_me!
    self.remember_token = "#{id}--#{Time.now.utc}"
    self.save
  end
 def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user  if user[:Password] == submitted_password
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :login
  has_many :complaints
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:username, :department, :compl_type, :subject, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
 def index
	@logins = Login.all
 end

 def new
    @login = Login.new
 end
 def show
  @user = Login.find(params[:id])
 end

 def create
  @login = Login.new(user_params)

    respond_to do |format|
      @login.save
    end
 end


#def checkLogin
 #   @log=Login.find_by email: @login.email
  #  if @log.Password == user_params.Password   
   #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #    format.json { render :show, status: :created, location: @user }
     # else
      #  format.html { render :new }
       # format.json { render json: @user.errors, status: :unprocessable_entity }
      #end
# end

private
    def set_user
      @login = Login.find(params[:id])
    end

    def user_params
      params.require(:login).permit(:email,:Password)
    end
end

app/controllers/pwds_controller.rb
class PwdsController < ApplicationController
	include PwdsHelper

 def new
  	@title="Forgot Password"
 end

 def create
   user=Login.find_by_email(params[:pwds][:email])
   if user.nil?
      render 'forgotPwd'
   else
   store user
   UserMailer.forgot_pwd(user).deliver
   end
   end


  def show
     render 'forgotPwd'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper
  def new
  	@title="Sign In"
  end
  def create
  	user = Login.authenticate(params[:session][:email],
                           params[:session][:password])
     if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
  else
  	sign_in user
    render 'userHome'
  end
  end

  def show

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
	@login = Login.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @login = Login.new({:email => @user.email, :Password => @user.name + "#123"})
    
  respond_to do |format|
     
      if @user.save
        @login.save    
	UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :address,:department, :designation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/pwds_helper.rb
module PwdsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user=(user)
    @current_user = user
  end
  def sign_in(user)

    user.remember_me!
    cookies[:remember_token] = { :value   => user.remember_token,
                                 :expires => 20.years.from_now.utc }
    self.current_user = user
  end
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def user_from_remember_token
    remember_token = cookies[:remember_token]
    User.find_by_remember_token(remember_token) unless remember_token.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/complaints/_form.html.erb
<%= form_for(@complaint) do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% @complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :Complaint_type %><br>
    <%= f.text_field :compl_type %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing complaint</h1>

<%= render 'form' %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<h1>Listing complaints</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Department</th>
      <th>Type</th>
      <th>Subject</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.username %></td>
        <td><%= complaint.department %></td>
        <td><%= complaint.compl_type %></td>
        <td><%= complaint.subject %></td>
        <td><%= complaint.phone %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<h1>New complaint</h1>

<%= render 'form' %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @complaint.username %>
</p>

<p>
  <strong>Department:</strong>
  <%= @complaint.department %>
</p>

<p>
  <strong>Type:</strong>
  <%= @complaint.compl_type %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @complaint.subject %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @complaint.phone %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>

app/views/home/index.html.erb
<h1>GOA UNIVERSITY</h1>
<h2>HELP DESK</h2>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Anup  Prajakta Aditya Raifen
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GUHD</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Foundation" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Foundation" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation" style="margin-top: -40px;">
  <div class="container-fluid">
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   '../login' %></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reservation <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="../gh_res/new">Guest House Reservation</a></li>
            <li><a href="../car_res/new">Vehicle Reservation</a></li>
            <li><a href="../hall_res/new">Seminar Hall Reservation</a></li>
          </ul>
        </li>
<li><%= link_to "Complaints",   '../complaints/new' %></li>
<li><%= link_to "Register",   '../users/new' %></li>

<li><%= link_to "Logout",   '../login' %></li>
      </ul>

      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
      
 

<h1 class="text-center">GOA UNIVERSITY</h1>
<h1 class="text-center">HELP DESK</h1>

    <div class="container">
      <%= yield %>
    </div>

</body>
<hr/>
   <nav class="navbar navbar-default navbar-fixed-bottom" >
  <div class="container">
  
    <h5 class="text-center"> &copy; GOA UNIVERSITY HELP DESK 2014</h5>
</div>
  </nav>

</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">hiii
    <%= f.label :Username %><br>
    <%= f.text_field :Username %>
  </div>
  <div class="field">
    <%= f.label :Password %><br>
    <%= f.text_field :Password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<div class="form-signin text-center">
<%= form_tag %>


<h2 class="form-signin-heading text-center">Please sign in</h2>
  
  
    <%= text_field "username", "name" , "class" => "form-control" , "placeholder" => "Username"%>
 <br/>
    <%= password_field "password", "name" , "class" => "form-control" , "placeholder" => "Password"%>
  
  
    <%= submit_tag "Sign In" , "class" => "btn btn-lg btn-primary btn-block input"%>   
    
  

<%= link_to "Forgot Password" %>
</form>
</div>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @login.Username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.Password %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/users/_form.html.erb
<div class="form-signin text-center">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h2 class="form-signin-heading text-center">Registration Form</h2>

  <div class="field">
    
    <%= f.text_field :name ,  "placeholder" => "Name"%>
  </div>
  <div class="field">
    
    <%= f.text_field :email,  "placeholder" => "Email"%>
  </div>
  <div class="field">

<div class="field">
    
    <%= f.text_field :address,  "placeholder" => "Address"%>
  </div>
    
    <%= f.text_field :phone,  "placeholder" => "Phone Number"%>
  </div>
<div class="field">
    
<div class="field">
 <%= f.select(:department, ['Department of Computer Science & Technology','Department of Management Studies','Department of Physics','Department of Chemistry','Department of Botany','Department of Commerce','Department of English'], {}, { :class => 'my_style_class' }) %>   


    
  </div>
  
  <div class="field">
   <%= f.select(:designation, ['HOD','Professor','Associate Professor','Assistant Professor','Student','Lab Assistant','Office Staff'], {}, { :class => 'my_style_class' }) %>   

    
  </div>
  <div class="actions">
    <%= f.submit "Register" , "class" => "btn btn-lg btn-primary btn-block input"%>   
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="panel panel-default">
  
  <div class="panel-heading">Listing users</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
	<th>Department</th>
      <th>Designation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
	
        <td><%= user.department %></td>
        <td><%= user.designation %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @user.designation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>